# Generated by Django 5.1 on 2024-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedi_empr', models.IntegerField()),
                ('pedi_fili', models.IntegerField()),
                ('pedi_nume', models.IntegerField()),
                ('pedi_forn', models.IntegerField()),
                ('pedi_data', models.DateTimeField()),
            ],
            options={
                'db_table': 'pedidosvenda',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=255),
        ),
    ]
