# Generated by Django 5.1 on 2024-08-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedidovenda_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('enti_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('enti_clie', models.IntegerField()),
                ('enti_nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidovenda',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_nume',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_forn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidades'),
        ),
    ]
