# Generated by Django 5.1 on 2024-08-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entidades_remove_pedidovenda_id_and_more'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_forn',
            field=models.ForeignKey(db_column='pedi_forn', on_delete=django.db.models.deletion.CASCADE, to='entidades.entidades'),
        ),
        migrations.DeleteModel(
            name='Entidades',
        ),
    ]
