# Generated by Django 5.1 on 2024-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pedidovenda_pedi_forn_delete_entidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contato_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_contato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
