# Generated by Django 5.1 on 2024-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_contato_realizado_pedido_data_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='contato_realizado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_contato',
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='contato_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='data_contato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
