# Generated by Django 5.1 on 2024-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pedido_contato_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='pedi_fina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='pedi_tota',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
    ]
