# Generated by Django 5.1 on 2024-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedidovenda_pedi_fina_pedidovenda_pedi_tota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='notas_contato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
