# Generated by Django 5.1 on 2024-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedidovenda_notas_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_nume',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
