# Generated by Django 5.1 on 2024-08-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pedidovenda_pedi_nume'),
        ('entidades', '0003_rename_enti_ema_entidades_enti_emai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='pedi_vend',
            field=models.ForeignKey(db_column='pedi_vend', default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_vendedor', to='entidades.entidades'),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_forn',
            field=models.ForeignKey(db_column='pedi_forn', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_fornecedor', to='entidades.entidades'),
        ),
    ]
