# Generated by Django 5.1 on 2024-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('codigo', models.CharField(db_column='fami_codi', max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='fami_desc', max_length=255)),
            ],
            options={
                'db_table': 'familiaprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('codigo', models.CharField(db_column='grup_codi', max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='grup_desc', max_length=255)),
            ],
            options={
                'db_table': 'gruposprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.CharField(db_column='marc_codi', max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='marc_nome', max_length=255)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produto_codigo', models.CharField(db_column='prod_codi', max_length=50, primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(db_column='prod_nome', max_length=255)),
                ('unidade_medida', models.CharField(db_column='prod_unme', max_length=10)),
                ('local', models.CharField(db_column='prod_loca', max_length=255)),
                ('ncm', models.CharField(db_column='prod_ncm', max_length=10)),
                ('codigo_fabricante', models.CharField(db_column='prod_codi_fabr', max_length=50)),
                ('foto', models.ImageField(blank=True, db_column='prod_foto', null=True, upload_to='fotos/')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaldoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(db_column='sapr_prod', max_length=50, unique=True)),
                ('empresa', models.CharField(db_column='sapr_empr', max_length=50)),
                ('filial', models.CharField(db_column='sapr_fili', max_length=50)),
                ('saldo_estoque', models.DecimalField(db_column='sapr_sald', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'saldosprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubgrupoProduto',
            fields=[
                ('codigo', models.CharField(db_column='sugr_codi', max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='sugr_desc', max_length=255)),
            ],
            options={
                'db_table': 'subgruposprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(db_column='tabe_prod', max_length=50, unique=True)),
                ('preco_custo', models.DecimalField(db_column='tabe_cuge', decimal_places=2, max_digits=10)),
                ('preco_a_vista', models.DecimalField(db_column='tabe_avis', decimal_places=2, max_digits=10)),
                ('preco_a_prazo', models.DecimalField(db_column='tabe_apra', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tabelaprecos',
                'managed': False,
            },
        ),
    ]
