# Generated by Django 5.1 on 2024-08-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('enti_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('enti_nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'entidades',
            },
        ),
    ]
