# Generated by Django 5.1 on 2024-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_remove_entidades_enti_empr_entidades_enti_celu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidades',
            old_name='enti_ema',
            new_name='enti_emai',
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_empr',
            field=models.IntegerField(default=1),
        ),
    ]
