# Generated by Django 5.1 on 2024-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uctabusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uciduser', models.IntegerField(blank=True, null=True)),
                ('ucusername', models.CharField(blank=True, max_length=30, null=True)),
                ('uclogin', models.CharField(blank=True, max_length=30, null=True)),
                ('ucpassword', models.CharField(blank=True, max_length=250, null=True)),
                ('ucpassexpired', models.CharField(blank=True, max_length=10, null=True)),
                ('ucuserexpired', models.IntegerField(blank=True, null=True)),
                ('ucuserdayssun', models.IntegerField(blank=True, null=True)),
                ('ucemail', models.CharField(blank=True, max_length=150, null=True)),
                ('ucprivileged', models.IntegerField(blank=True, null=True)),
                ('uctyperec', models.CharField(blank=True, max_length=1, null=True)),
                ('ucprofile', models.IntegerField(blank=True, null=True)),
                ('uckey', models.CharField(blank=True, max_length=250, null=True)),
                ('ucinative', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uctabusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usua_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('usua_nome', models.CharField(blank=True, max_length=30, null=True)),
                ('usua_data_nasc', models.DateField(blank=True, null=True)),
                ('usua_sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('usua_emai', models.CharField(blank=True, max_length=100, null=True)),
                ('usua_fone', models.CharField(blank=True, max_length=14, null=True)),
                ('usua_senh', models.CharField(blank=True, max_length=10, null=True)),
                ('usua_libe_clie_bloq', models.BooleanField(blank=True, null=True)),
                ('usua_libe_pedi_comp', models.BooleanField(blank=True, null=True)),
                ('usua_port', models.BooleanField(blank=True, null=True)),
                ('usua_pisc', models.BooleanField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
